# Generated by Django 5.2.16 on 2026-07-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0005_remove_experiment_comments_remove_experiment_design_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='purity',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='chemical',
            name='composition_purity',
            field=models.CharField(blank=True, choices=[('ANA', 'analytical grade'), ('TCH', 'technical grade'), ('NS', 'purity not specified'), ('NA', 'not applicable (e.g. in silico study)'), ('OTH', 'other')], help_text="If detailed information on the purity of the composition is not known, a qualitative statement can be provided in this field, e.g. 'analytical grade' or 'technical grade'.<p>A chemical can be created for a mixture/product. If the chemical refers to the composition of the mixture/product, in the field % purity, specify the chemical composition.", max_length=3, verbose_name='Composition / Purity'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='composition_purity_other',
            field=models.CharField(blank=True, default='', verbose_name='Other Composition / Purity Details'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Provide the expiration date or re-test date', null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='lot_batch_num',
            field=models.CharField(blank=True, default='', help_text='Lot and batch number', max_length=255, verbose_name='Lot / Batch #'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='percent_purity',
            field=models.CharField(blank=True, default='', help_text='Provide the % purity or chemical composition', max_length=255, verbose_name='% Purity'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='reactivity',
            field=models.TextField(blank=True, help_text='Provide information on any known reactivity of the test material with the incubation material used (e.g. binding to plastic ware or adsorption)', max_length=2000),
        ),
        migrations.AddField(
            model_name='chemical',
            name='solubility',
            field=models.CharField(blank=True, choices=[('YES', 'The highest tested concentration was soluble'), ('NO', 'The highest tested concentration was insoluble, specify'), ('UNK', 'Unknown')], help_text='It should be confirmed that the highest concentration tested was soluble, in case not, a justification should be provided.<p>Please specify the highest soluble concentration observed. If the highest tested concentration was insoluble, provide a justification for why insoluble concentrations were tested.', max_length=3),
        ),
        migrations.AddField(
            model_name='chemical',
            name='solubility_details',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chemical',
            name='stability',
            field=models.CharField(blank=True, choices=[('STA', 'The chemical is stable under storage and assay conditions, specify'), ('UNK', 'Unknown')], help_text='Select the appropriate information about stability of the chemical under storage conditions and under assay conditions.<p>In case this was not assessed or reported, select ‘unknown’', max_length=3),
        ),
        migrations.AddField(
            model_name='chemical',
            name='stability_details',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='name',
            field=models.CharField(help_text='This field may get displayed in visualizations, so consider using a common acronym, e.g., BPA instead of Bisphenol A', max_length=255, verbose_name='Chemical name'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='source',
            field=models.CharField(blank=True, help_text='Company and catalog number if available', max_length=255, verbose_name='Source of chemical'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='has_guideline',
            field=models.CharField(blank=True, choices=[('YS', 'Yes'), ('NO', 'No'), ('NR', 'Not reported')], default='', help_text='Select whether a guideline study was conducted. If yes, enter the Test Guideline number in the Guideline Comments fields.', max_length=2, verbose_name='Guideline'),
        ),
    ]
