# Generated by Django 5.2.16 on 2026-08-31 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0009_remove_chemical_experiment_chemical_study'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='Any pertinent information regarding a substance’s origin (the corporation, organization, or facility that produced the substance) and catalog number if available. \nOther notable information about the test substance in general or special handling of the chemical, such as milling, can be noted in this field.', max_length=255)),
                ('composition', models.CharField(blank=True, choices=[('MET', 'metabolite'), ('MIX', 'mixture'), ('MUL', 'multiple substances'), ('FOR', 'formulation'), ('PAR', 'parent')], default='', help_text='A chemical can be created for a mixture/product. If the chemical refers to the composition of the mixture/product. Select the chemical composition and specify the chemical composition in the “Composition Remarks” field.', max_length=3)),
                ('composition_remarks', models.CharField(help_text='Specify the chemical composition.', max_length=255)),
                ('purity', models.CharField(blank=True, choices=[('AN', 'analytical grade'), ('TE', 'technical grade'), ('NS', 'purity not specified'), ('NA', 'not applicable (e.g. in silico study) ')], default='', help_text="If detailed information on the purity of the composition is not known, a qualitative statement can be provided in this field, e.g. 'analytical grade' or 'technical grade'.", max_length=2)),
                ('percent_purity', models.CharField(help_text='Provide the % purity or chemical composition', max_length=255, verbose_name='% Purity')),
                ('expiration_date', models.DateTimeField(help_text='Provide the expiration date or re-test date')),
                ('lot_batch_number', models.CharField(help_text='Lot or batch number assigned to chemical by chemical supplier. Leave blank if this information is not reported within the document.', max_length=255, verbose_name='Lot / Batch #')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsubstances', to='animalv2.chemical')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testsubstances', to='animalv2.experiment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
