# Generated by Django 5.2.16 on 2026-09-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0010_testsubstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubstance',
            name='expiration_date',
            field=models.DateField(help_text='Provide the expiration date or re-test date'),
        ),
    ]
