# Generated by Django 5.2.16 on 2026-09-03 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0011_alter_testsubstance_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline_status', models.CharField(blank=True, choices=[('YS', 'Yes'), ('NO', 'No'), ('NR', 'Not reported')], default='', help_text='Select whether a guideline study was conducted.', max_length=2)),
                ('name', models.CharField(blank=True, help_text='Name of the Office of Chemical Safety and Pollution Prevention (OCSPP) Health Effects or OECD (Organization for Economic Cooperation and Development) guideline to which a study (most closely) adheres to.', max_length=255, verbose_name='Guideline name')),
                ('number', models.CharField(blank=True, help_text='Number associated with the OCSPP or OECD guideline that a study (most closely) adheres to. Guideline numbers are differentiated by the distinct number proceeding 870/890, as dictated by the EPA Health Effects Test Guidelines. \nThe guideline number should be entered in the box with both the acronym and full number. For example, “OPPTS 870.3700.”', max_length=255, verbose_name='Guideline number')),
                ('version_year', models.CharField(blank=True, help_text='Describe the guideline version/year', max_length=255, verbose_name='Guideline Version/Year')),
                ('deviations', models.TextField(blank=True, help_text='List each deviation from the protocol and classify the deviation as major or minor.  Also report any rationale provided by the investigator’s for the deviation.  Similarly list, classify, and discuss all other deficiencies with the conduct, results, and reporting of the study.  Discuss the possibility of resolving the deficiencies and what would be required.  Major deficiencies may be presented and discussed in paragraph form, whereas minor deficiencies can be presented in a bulleted list.', max_length=1500, verbose_name='Guideline Deviations')),
                ('compliance', models.CharField(blank=True, choices=[('YS', 'Yes'), ('NO', 'No'), ('NR', 'Not reported')], default='', help_text='Are GLP and Quality Assurance statements provided, signed, and dated?', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guidelines', to='animalv2.experiment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
