# Generated by Django 5.2.16 on 2026-09-04 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0012_guideline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsubstance',
            name='composition_remarks',
            field=models.CharField(blank=True, help_text='Specify the chemical composition.', max_length=255),
        ),
        migrations.CreateModel(
            name='AnimalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name should be sex, common strain name, species (plural) and use Title Style (e.g. Male Sprague Dawley Rat). For developmental toxicity and reproduction studies include the generation before the sex in title (e.g. F1 Male Sprague Dawley Rat or P0 Female C57 Mice). For cohort type include', max_length=255, verbose_name='Animal Group Name')),
                ('generation', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('F0', 'F0'), ('F1', 'F1'), ('F2', 'F2'), ('UN', 'unknown/not reported'), ('OT', 'other')], default='', help_text='Generation of the test animal group. F0: The default choice for animals exposed in non-reproductive studies (chronic CHR, subchronic SUB, subacute SAC), dams in reproductive DEV studies, and the first-generation mating group for multigenerational MGR studies. F1: The second generation, born to F0. F2: The third generation, born to F1. F3: The fourth generation, born to F2. Fetal: The fetal generation is the group produced by F0 matings in DEV studies, typically removed from a female via cesarean section. Pups from live births are not fetal.', max_length=2)),
                ('generation_remarks', models.CharField(blank=True, default='', help_text='Specify the generation of the test animal for "other"', max_length=255)),
                ('cohort_type', models.CharField(choices=[('SAT', 'satellite'), ('REC', 'recovery'), ('SEN', 'sentinel'), ('INT', 'interim'), ('TER', 'terminal'), ('PM1', 'post first mating'), ('PM2', 'post second mating'), ('PM3', 'post third mating'), ('OTH', 'other')], default='', help_text='Select the term from the list below that best characterizes when the treatment group was evaluated for effects.<br><em>Satellite</em>: Group of animals included in the design and conduct of a toxicity study, treated, and housed under conditions identical to those of the main study animals, but used primarily for some separate purpose to be defined as needed in the Comment section.<br><em>Recovery</em>: Group examined after a recovery period that followed the dosing period at the end of the study. Recovery groups will have explicitly stated recovery periods. For example, if dosing stopped on day 15 and animals were sacrificed and examined on day 16 or later, this would be considered terminal and not recovery unless the study explicitly defines this time as recovery.<br><em>Sentinel</em>: Group used primarily for health or microbiological monitoring, not endpoint evaluation.<br><em>Interim</em>: Group sacrificed and examined within the dosing period.<br><em>Terminal</em>: Group sacrificed and examined at study completion and after the dosing period. These animals are not mated.<br><em>Post first mating</em>: Group examined after first mating.<br><em>Post second mating</em>: Group examined after second mating.<br><em>Post third mating</em>: Group examined after third mating.<br><em>Other</em>: Group of animals that may have deviated from the full study design, to be defined as needed in the “Cohort Type Remarks” field.', max_length=3)),
                ('cohort_type_remarks', models.CharField(blank=True, default='', help_text='If “other” is selected for Cohort Type, describe the animal group.', max_length=255)),
                ('source', models.CharField(choices=[('COM', 'commercial supplier, specify'), ('NON', 'non-commercial supplier, specify'), ('HOU', 'In-house developed, specify'), ('OTH', 'other')], default='', max_length=3, verbose_name='Animal Source')),
                ('source_remarks', models.CharField(blank=True, help_text='Provide information on the source of the animal species and strain using complete genetic nomenclature. Provide the supplier’s name and address (if available)', max_length=255, verbose_name='Animal Source Remarks')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MF', 'Combined'), ('NS', 'not specified')], default='', max_length=2)),
                ('number_of_animals', models.CharField(blank=True, help_text='Provide the full number of animals included in the study.', max_length=255)),
                ('age_and_condition', models.CharField(blank=True, help_text='Provide age, health status (e.g. good health, animal model of disease, etc.) and body weight range', max_length=255, verbose_name='Animal Age and Condition')),
                ('acclimatization', models.TextField(blank=True, help_text='Describe the acclimatization period and animal husbandry conditions prior to the initiation of test method.', max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniv2_animalgroups', to='animalv2.experiment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
