# Generated by Django 5.2.16 on 2026-09-04 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0013_alter_testsubstance_composition_remarks_animalgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Husbandry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_per_cage', models.CharField(help_text='Provide the number of animals per cage.', max_length=255, verbose_name='Number of Animals per Cage')),
                ('animal_randomization', models.CharField(choices=[('YES', 'yes, with remarks'), ('NO', 'no'), ('OTH', 'other'), ('UNK', 'unknown')], help_text="Select whether a randomization method was used to assign animals to cages. If yes, include a description of animal randomization method. If not available from picklist, select 'other' and specify", max_length=3)),
                ('animal_randomization_remarks', models.CharField(blank=True, max_length=255)),
                ('cage_material', models.CharField(choices=[('GLA', 'glass'), ('PCA', 'polycarbonate'), ('PPR', 'polypropylene'), ('PT', 'Polyethylene terepthalate'), ('SS', 'stainless steel'), ('ALU', 'aluminum'), ('MSH', 'wire mesh'), ('ACR', 'acrylic'), ('OTH', 'other'), ('NS', 'not specified')], help_text="Select animal cage material. If not available from picklist, select 'other' and specify.", max_length=3)),
                ('cage_material_remarks', models.CharField(blank=True, max_length=255)),
                ('bedding_material', models.CharField(choices=[('WOO', 'wood shavings'), ('PAP', 'paper'), ('COB', 'corn cob'), ('HAY', 'hay or straw'), ('COC', 'coconut fibre (coir)'), ('PEL', 'pelleted'), ('FLC', 'fleece'), ('OTH', 'other'), ('NS', 'not specified')], help_text="Select the animal bedding material. If not available from picklist, select 'other' and specify.", max_length=3)),
                ('bedding_material_remarks', models.CharField(blank=True, max_length=255)),
                ('enrichment_material', models.CharField(choices=[('SHE', 'structural (shelter/hiding place)'), ('PLA', 'structural (platform or perch)'), ('CLB', 'structural (branches or climbing structure)'), ('TOY', 'manipulative (toys and objects)'), ('FOR', 'manipulative (foraging devices)'), ('CHW', 'manipulative (chewable items)'), ('VIS', 'sensory (visual stimuli)'), ('AUD', 'sensory (auditory stimuli)'), ('OLF', 'sensory (olfactory stimuli)'), ('ENV', 'environmental (natural materials)'), ('PUZ', 'cognitive (puzzle feeders)'), ('TRA', 'cognitive (training and tasks)'), ('OTH', 'other'), ('NS', 'not specified')], help_text="Select the type of enrichment provided for animals. If none apply, select “other” and describe the test material. If not available from picklist, select 'other' and specify.", max_length=3)),
                ('enrichment_material_remarks', models.CharField(blank=True, max_length=255)),
                ('water_bottle_material', models.CharField(choices=[('GLA', 'glass'), ('PCA', 'polycarbonate'), ('PPR', 'polypropylene'), ('PT', 'Polyethylene terepthalate'), ('SS', 'stainless steel'), ('OTH', 'other'), ('NS', 'not specified')], help_text="Select the water bottle material. If not available from picklist, select 'other' and specify.", max_length=3)),
                ('water_bottle_material_remarks', models.CharField(blank=True, max_length=255)),
                ('animal_identification', models.CharField(choices=[('EAN', 'ear notch'), ('EAT', 'ear tag'), ('CHP', 'microchip'), ('TAT', 'tattoo'), ('TOE', 'toe clipping'), ('FRC', 'fur clipping'), ('FRD', 'fur dyeing'), ('COL', 'collar or band'), ('PAI', 'paint or marker'), ('NAT', 'natural markings'), ('OTH', 'other'), ('NS', 'not specified')], help_text="Select the animal identification method. If not available from picklist, select 'other' and specify.", max_length=3)),
                ('animal_identification_remarks', models.CharField(blank=True, max_length=255)),
                ('ambient_temperature', models.CharField(help_text='Describe the animal husbandry temperature.', max_length=255, verbose_name='Ambient Temperature (°C)')),
                ('humidity_percentage', models.CharField(help_text='Describe the animal husbandry humidity in %', max_length=255, verbose_name='Humidity (%)')),
                ('photo_period', models.CharField(help_text='Describe the photoperiod as hours dark / hours light.', max_length=255, verbose_name='Photoperiod (hrs dark / hrs light)')),
                ('feeding_frequency', models.CharField(choices=[('ADL', 'ad libitum'), ('OTH', 'other, specify'), ('NS', 'not specified')], help_text='Select the feeding frequency and provide additional details in the “Animal Feeding and Diet Remarks” field.', max_length=3)),
                ('diet', models.CharField(choices=[('CON', 'conventional'), ('RES', 'calorie restricted'), ('FAS', 'fasted'), ('NS', 'not specified')], help_text='Select the type of diet (e.g. conventional laboratory diet / caloric restriction), whether it was provided ad libitum, restricted, etc. ', max_length=3)),
                ('feeding_and_diet_remarks', models.TextField(help_text='Describe the animal feeding protocol. For fasting, describe the fasting protocol (e.g. animals were fasted 4 hours prior to sacrifice).', max_length=32768)),
                ('water', models.CharField(choices=[('TAP', 'tap water'), ('FIL', 'filtered water'), ('DEI', 'deionized water'), ('DIS', 'distilled water'), ('RVO', 'reverse osmosis water'), ('STR', 'sterile water'), ('ACI', 'acidified water'), ('SUP', 'supplemented water'), ('OTH', 'other'), ('NS', 'not specified')], help_text="Describe type (e.g. drinking water, tap distilled), and whether it was provided ad libitum. If not available from picklist, select 'other' and specify.", max_length=3)),
                ('food_and_water_quality', models.TextField(help_text='Provide analytical information (if available) on the nutrient and dietary contaminant levels. Similarly provide analytical information on the drinking water used in the study.', max_length=2500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('animal_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husbandries', to='animalv2.animalgroup')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='husbandries', to='animalv2.experiment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
