# Generated by Django 5.2.16 on 2026-09-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0014_husbandry'),
    ]

    operations = [
        migrations.AddField(
            model_name='husbandry',
            name='water_remarks',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
