# Generated by Django 5.2.16 on 2026-09-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0015_husbandry_water_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_of_exposure', models.CharField(choices=[('ORA', 'oral'), ('SCU', 'subcutaneous'), ('DER', 'dermal'), ('INH', 'inhalation'), ('INJ', 'injection'), ('OCU', 'ocular'), ('OTH', 'other, specify')], help_text="Select the route of administration as appropriate. If not available from the picklist, select 'other' and specify.", max_length=3)),
                ('route_of_exposure_remarks', models.CharField(blank=True, help_text='If “other” was selected in the “Route of exposure” field, specify.', max_length=250)),
                ('exposure_method', models.CharField(choices=[('ORCAP', 'oral capsule'), ('ORDIE', 'oral diet'), ('ORGAV', 'oral gavage'), ('ORWAT', 'oral drinking water'), ('INGAS', 'inhalation - gas'), ('INPAR', 'inhalation - particle'), ('INVAP', 'inhalation - vapor'), ('DERM', 'dermal'), ('IJSUB', 'subcutaneous injection'), ('IJPER', 'intraperitoneal injection'), ('IJIV', 'intravenous injection'), ('INOVO', 'in ovo'), ('PAREN', 'parental'), ('BODY', 'whole body'), ('MULTI', 'multiple'), ('UNKWN', 'unknown'), ('OTHER', 'other')], help_text='Specific description of how substance was given to test subjects via the administration route.', max_length=5)),
                ('exposure_method_remarks', models.CharField(blank=True, help_text='If “other” was selected in the “Route of exposure” field, specify.', max_length=250)),
                ('lifestage_start', models.CharField(choices=[('EMB', 'embryonic'), ('FET', 'fetal'), ('NEO', 'neonate'), ('JUV', 'juvenile'), ('ADO', 'adolescent'), ('ADU', 'adult'), ('SEN', 'senior'), ('NA', 'NA')], help_text='Embryonic Stage:<br>Description: The initial stage of development within the egg or womb, where the organism begins to form and differentiate.<br>Characteristics: Rapid cell division and formation of basic body structures.<p>Fetal:<br>Later stage of development within the eff or womb characterized by continued growth, differentiation, and maturation of organs and tissues. <br> Characteristics: The organism has an established body-plan and recognizable anatomical features but remains dependent on the maternal environment for development. <p> Neonatal Stage:<br>Description: The period immediately after birth or hatching.<br> Characteristics: Animals are usually highly dependent on parental care and nourishment.<p> Juvenile Stage:<br>Description: The phase following the neonatal stage, where the animal grows and develops but is not yet sexually mature.<br>Characteristics: Increased independence, rapid growth, and learning survival skills.<p>Adolescent Stage:<br>Description: The transition phase between juvenile and adult stages, marked by the onset of puberty.<br>Characteristics: Development of secondary sexual characteristics and increased social interactions.<p>Adult Stage:<br>Description: The stage where the animal is fully grown and sexually mature.<br>Characteristics: Reproductive capability and establishment of social hierarchies or territories.<p>Senior Stage:<br>Description: The later stage of life where the animal experiences aging and a decline in physical capabilities.<br>Characteristics: Reduced reproductive capability and increased susceptibility to disease.', max_length=3, verbose_name='Animal Lifestage at the Start of Exposure')),
                ('age_start', models.CharField(help_text='Record the age of animals at the start of test item administration.', max_length=255, verbose_name='Animal Age at Start of Exposure')),
                ('age_start_unit', models.CharField(choices=[('D', 'Day'), ('DPM', 'day (premating)'), ('DGE', 'GD (gestational day)'), ('DPN', 'PND (post-natal day)'), ('W', 'week'), ('WPM', 'week (premating)'), ('MON', 'month'), ('YEA', 'year'), ('GEN', 'generation')], help_text='Record the animal age unit of measure.', max_length=3, verbose_name='Animal Age at Start Unit')),
                ('age_end', models.CharField(help_text='Record the age of animals at the start of test item administration.', max_length=255, verbose_name='Animal Age at End of Exposure')),
                ('age_end_unit', models.CharField(choices=[('D', 'Day'), ('DPM', 'day (premating)'), ('DGE', 'GD (gestational day)'), ('DPN', 'PND (post-natal day)'), ('W', 'week'), ('WPM', 'week (premating)'), ('MON', 'month'), ('YEA', 'year'), ('GEN', 'generation')], help_text='Record the animal age unit of measure.', max_length=3, verbose_name='Animal Age at End Unit')),
                ('verification', models.CharField(choices=[('YS', 'yes'), ('NO', 'no'), ('NS', 'not specified')], help_text='Were concentrations/doses analytically verified in the experiment?', max_length=3, verbose_name='Analytical Verification of Doses or Concentrations')),
                ('exposure_duration', models.CharField(help_text="Indicate duration in days, weeks or months, e.g. '104 weeks' or '90 days'.", max_length=255)),
                ('frequency_of_treatment', models.CharField(help_text="Indicate the frequency of the administration of doses to the test animals (e.g., 'daily, 7 days each week'). Use of non-standard dosing regimen (e.g. a five-day per week regime) should be justified.", max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='animalv2.experiment')),
                ('test_substance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='animalv2.testsubstance')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
