# Generated by Django 5.2.16 on 2026-09-15 19:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0016_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_group_type', models.CharField(choices=[('VEC', 'Vehicle Control'), ('UNC', 'Untreated Control'), ('PFC', 'Pair-fed Control'), ('REF', 'Reference / Comparator'), ('TRT', 'Treatment'), ('OTH', 'Other')], help_text='Select the role of the dose group within the experiment.', max_length=3)),
                ('dose_group_type_remarks', models.CharField(blank=True, help_text='If “other” was selected in the “Dose Group Type” field, specify.', max_length=250)),
                ('dose_value', models.FloatField(help_text='Numerical concentration value of a test chemical. If a study changes dosing over time (e.g., gradually increased over a few weeks, decreased due to palatability or toxicity), enter final concentrations. You do not need to calculate the average. In unusual cases, not all doses will be converted from ppm to mg/kg/day. Enter the mixed dosing units (do not attempt conversion), unless only one dose is converted. If only one dose is converted (often the critical effect dose) then put the conversion(s) in the comments and keep all doses as ppm.', validators=[django.core.validators.MinValueValidator(0)])),
                ('dose_units', models.CharField(choices=[('PPM', 'ppm (in air, water, or food)'), ('MGDAY', 'mg/kg-bw/day'), ('MGKG', 'mg/kg'), ('MGM3', 'mg/m3'), ('MGMLW', 'mg chemical/mL water'), ('MGLAI', 'mg chemical/L air'), ('MGEYE', 'mg/eye'), ('OTHER', 'other'), ('NS', 'not specified')], help_text='Unit associated with a concentration of a test chemical. Preferred unit is milligrams per kilogram per day (mg/kg/day) if reported. If the mg/kg/day is not reported based on ppm or other units, do not attempt to estimate the mg/kg/day dose.', max_length=5)),
                ('dose_units_remarks', models.CharField(blank=True, help_text='If “other” was selected in the “Dose Units” field, specify.', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('animal_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniv2_dosegroups', to='animalv2.animalgroup')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniv2_dosegroups', to='animalv2.experiment')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniv2_dosegroups', to='animalv2.treatment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
