# Generated by Django 5.2.16 on 2026-09-16 19:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animalv2', '0017_dosegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DosePreparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(choices=[('UNCHA', 'unchanged (no vehicle)'), ('ACET', 'acetone'), ('AROIL', 'arachis oil'), ('BEEWX', 'beeswax'), ('CBOWX', 'carbowaxes'), ('CAOIL', 'castor oil'), ('CTSAL', 'cetosteryl alcohol'), ('CETAL', 'cetyl alcohol'), ('CMC', 'CMC (carboxymethyl cellulose)'), ('CCOIL', 'coconut oil'), ('CROIL', 'corn oil'), ('CSOIL', 'cotton seed oil'), ('DMSO', 'DMSO'), ('ETHAN', 'ethanol'), ('GLYES', 'glycerol ester'), ('GLYCO', 'glycolester'), ('HVOIL', 'hydrogenated vegetable oil'), ('LECIT', 'lecithin'), ('MACES', 'macrogel ester'), ('MZOIL', 'maize oil'), ('MECEL', 'methylcellulose'), ('OLOIL', 'olive oil'), ('PAOIL', 'paraffin oil'), ('PEOIL', 'peanut oil'), ('PETLA', 'petrolatum'), ('PHSAL', 'physiological saline'), ('POLOX', 'poloxamer'), ('POGLY', 'polyethylene glycol'), ('PRGLY', 'propylene glycol'), ('SIOIL', 'silicone oil'), ('SRDER', 'sorbitan derivative'), ('SYOIL', 'soya oil'), ('THOIL', 'theobroma oil'), ('VGOIL', 'vegetable oil'), ('WATER', 'water'), ('OTHER', 'other'), ('NS', 'not specified')], help_text="The media used in administration of the chemical. Select the vehicle used. If not available from picklist, select 'other' and specify. Further information can be given in the supplementary remarks field.<p>Note that some of the vehicles provided in this list are used for specific routes of administration only.", max_length=5)),
                ('vehicle_remarks', models.CharField(blank=True, help_text='If “other” was selected in the “Vehicle” field, specify.', max_length=250)),
                ('concentration', models.FloatField(help_text='Enter numerical value of all doses tested (numerical value only, e.g. 1, 3, 30, etc.)', validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('PPM', 'ppm (in air, water, or food)'), ('MGDAY', 'mg/kg-bw/day'), ('MGKG', 'mg/kg'), ('MGM3', 'mg/m3'), ('MGMLW', 'mg chemical/mL water'), ('MGLAI', 'mg chemical/L air'), ('MGEYE', 'mg/eye'), ('OTHER', 'other'), ('NS', 'not specified')], help_text='Enter the numerical value and concentration units from the picklist. If “other” is selected, indicate the units in the “Unit Remarks” field.', max_length=5)),
                ('unit_remarks', models.CharField(blank=True, help_text='If “other” was selected in the “Unit” field, specify.', max_length=250)),
                ('formulation_type', models.CharField(choices=[('SOL', 'solution'), ('SUS', 'suspension'), ('EMU', 'emulsion'), ('DIS', 'dispersion'), ('NEA', 'neat / undiluted'), ('DIE', 'diet admixture'), ('DWA', 'drinking water preparation'), ('OTH', 'other'), ('NS', 'not specified')], help_text='Select the appropriate information about formulation type of the test substance under storage conditions and under assay conditions.', max_length=3)),
                ('formulation_type_remarks', models.CharField(blank=True, help_text='If “other” was selected in the “Formulation Type” field, specify.', max_length=250)),
                ('stability', models.CharField(choices=[('STA', 'The chemical is stable under storage and assay conditions, specify'), ('UNK', 'Unknown')], help_text='Select the appropriate information about stability of the chemical under storage conditions and under assay conditions.<p>In case this was not assessed or reported, select ‘unknown’', max_length=3, verbose_name='Stability in Vehicle')),
                ('solubility', models.CharField(choices=[('SOL', 'The highest tested concentration was soluble'), ('INS', 'The highest tested concentration was insoluble, specify '), ('UNK', 'Unknown')], help_text='It should be confirmed that the highest concentration tested was soluble, in case not, a justification should be provided.<p>Specify the highest soluble concentration observed. If the highest tested concentration was insoluble, provide a justification for why insoluble concentrations were tested in the “Solubility Remarks” field. the appropriate information about stability of the chemical under storage conditions and under assay conditions.<p>In case this was not assessed or reported, select ‘unknown’', max_length=3, verbose_name='Solubility in Vehicle')),
                ('solubility_remarks', models.CharField(blank=True, help_text='If “The highest tested concentration was insoluble, specify” was selected in the “Solubility in Vehicle” field, specify.', max_length=250, verbose_name='Solubility in Vehicle Remarks')),
                ('homogeneity', models.CharField(choices=[('DEM', 'Demonstrated'), ('NDM', 'Not demonstrated'), ('NEV', 'Not evaluated'), ('NR', 'Not Reported')], help_text='Select the appropriate information about homogeneity under dose preparation conditions. Provide details in the remarks field.', max_length=3)),
                ('analytical_verification', models.CharField(choices=[('VER', 'Verified'), ('NVR', 'Not Verified'), ('NEV', 'Not evaluated'), ('NR', 'Not Reported')], help_text='Select the appropriate information about analytical verification under dose preparation conditions. Provide details in the remarks field for the analytical method used.', max_length=3)),
                ('analytical_verification_remarks', models.CharField(blank=True, help_text='Provide details for the analytical method used.', max_length=250)),
                ('preparation_frequency', models.CharField(choices=[('DAY', 'Daily'), ('EAC', 'Each Dosing'), ('WKL', 'Weekly'), ('PER', 'Periodic'), ('SIN', 'Single preparation'), ('OTH', 'Other'), ('NR', 'Not Reported')], help_text='Select the appropriate information about preparation frequency under dose preparation conditions. Provide details in the remarks field.', max_length=3)),
                ('preparation_frequency_remarks', models.CharField(blank=True, help_text='If “Other” was selected in the “Preparation Frequency” field, specify the preparation frequency.', max_length=250)),
                ('preparation_method', models.CharField(choices=[('DIS', 'Dissolved'), ('SUS', 'Suspended'), ('MIX', 'Mixed'), ('DIL', 'Diluted'), ('DIE', 'Incorporated Into Diet'), ('DWA', 'Incorporated Into Drinking Water'), ('NEA', 'Used Neat'), ('OTH', 'Other'), ('NR', 'Not Reported')], help_text='Select the appropriate information about preparation method under dose preparation conditions. Provide details in the remarks field.', max_length=3)),
                ('preparation_method_remarks', models.CharField(blank=True, help_text='If “Other” was selected in the “Preparation Method” field, specify the preparation frequency.', max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('dose_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniv2_dosepreparations', to='animalv2.dosegroup')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aniv2_dosepreparations', to='animalv2.experiment')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
